version: '3'
services:
  backend:
    build: ./
    container_name: account_management_service
    ports:
      - '3100:3100'
    depends_on:
      - postgres
    networks:
      - collabvr_network
    env_file:
      - .env

  postgres:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ".postgres-backend:/data/db"
    networks:
      - collabvr_network

networks:
  collabvr_network:
    driver: bridge
