version: '3'
services:
  backend:
    build: ./
    container_name: account_management_service
    environment:
      - DATABASE_URL="postgresql://postgres:123@postgresql_db  :5434/nest?schema=public"
      - JWT_ACCESS_TOKEN_SECRET="jwtSecret2023"
      - JWT_REFRESH_TOKEN_SECRET="jwtSecret2023"
      - MAIL_HOST=smtp.gmail.com
      - MAIL_USER=diegojohnson46@gmail.com
      - MAIL_PASSWORD=ldojbhdjqtggyrun
      - MAIL_FROM=diegojohnson46@gmail.com
      - PORT=3100
    ports:
      - '3100:3100'
    depends_on:
      - database
    networks:
      - collabvr_network

  database:
    image: postgres:13
    container_name: postgresql_db
    ports:
      - 5434:5432
    volumes:
      - ".postgres-backend:/data/db"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - collabvr_network

networks:
  collabvr_network:
    driver: bridge
