version: '3'
services:
  backend:
    build: ./
    container_name: account_management_service
    ports:
      - '${BACKEND_PORT}:3000'
    depends_on:
      - accounts_db
    networks:
      - collabvr_network
    env_file:
      - .env

  accounts_db:
    image: postgres:13
    container_name: accounts_db
    env_file:
      - .env
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ".postgres-backend:/data/db"
    networks:
      - collabvr_network

networks:
  collabvr_network:
    driver: bridge
